### PR TITLE
Added python section

### PR DESCRIPTION
**Pull request by VishalRohra**
Added the python section. Not sure why it wasn't already there.

### CODE REVIEW

**Comment by CuriousLearner** [comment]
Your second commit is same as what @sahilshekhawat has done in #4 . This is nice but it isn't working correctly for all links as I mentioned in the PR. Also for the PDF the anchor isn't working correctly. It would be great if you inspect the issue.

Else, we can go ahead adding just the `Python` category to the scrapper.

**Comment by CuriousLearner** [comment]
Let me know what you think about this @VishalRohra

**Comment by VishalRohra** [comment]
Sorry, messed up on branching. Not sure how to fix it for all links. Please go ahead with the first commit.

**Comment by CuriousLearner** [comment]
@VishalRohra Just hard reset to first commit via
`git reset --hard  d991bdc`

Then do force push to your branch
`git push <remote-name> <branch-name> -f`

It's okay to make mistakes, what is really essential is that you learn from them :)
Please do the changes, and I'll merge them. Thanks for your contributions.

**Comment by CuriousLearner** [comment]
This looks good to me! I'm squashing and merging the commit. I hope you've learned some git. If you need any help, please feel free to ping me.

Thanks for your contributions.

**Pull request merged**
